/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { SkillDeleteResult, SkillDetail, SkillImportResult, SkillScope, SkillView } from '@dsh-plugins/skill-panel/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$736b696c6c41646d696e {
    deleteSkill: (scope: SkillScope, name: string) => Promise<RemoteResult<SkillDeleteResult>>
    importZip: (scope: SkillScope, base64: string, overwrite: boolean) => Promise<RemoteResult<SkillImportResult>>
    list: (scope: SkillScope) => Promise<RemoteResult<SkillView[]>>
    readSkill: (scope: SkillScope, name: string) => Promise<RemoteResult<SkillDetail>>
  }
  interface TypertRemoteMap {
    'skillAdmin/deleteSkill': (scope: SkillScope, name: string) => Promise<RemoteResult<SkillDeleteResult>>
    'skillAdmin/importZip': (scope: SkillScope, base64: string, overwrite: boolean) => Promise<RemoteResult<SkillImportResult>>
    'skillAdmin/list': (scope: SkillScope) => Promise<RemoteResult<SkillView[]>>
    'skillAdmin/readSkill': (scope: SkillScope, name: string) => Promise<RemoteResult<SkillDetail>>
  }
  interface TypertRemoteNamespaceMap {
    'skillAdmin': TypertRemoteNamespace$736b696c6c41646d696e
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
