/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { McpServerConfig, McpServerView, McpToolView, McpWriteResult } from '@dsh-plugins/mcp-panel/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$6d637041646d696e {
    deleteServer: (serverName: string) => Promise<RemoteResult<McpWriteResult>>
    getTools: (serverName: string) => Promise<RemoteResult<McpToolView[]>>
    list: () => Promise<RemoteResult<McpServerView[]>>
    setEnabled: (serverName: string, enabled: boolean) => Promise<RemoteResult<McpWriteResult>>
    upsert: (config: McpServerConfig) => Promise<RemoteResult<McpWriteResult>>
  }
  interface TypertRemoteMap {
    'mcpAdmin/deleteServer': (serverName: string) => Promise<RemoteResult<McpWriteResult>>
    'mcpAdmin/getTools': (serverName: string) => Promise<RemoteResult<McpToolView[]>>
    'mcpAdmin/list': () => Promise<RemoteResult<McpServerView[]>>
    'mcpAdmin/setEnabled': (serverName: string, enabled: boolean) => Promise<RemoteResult<McpWriteResult>>
    'mcpAdmin/upsert': (config: McpServerConfig) => Promise<RemoteResult<McpWriteResult>>
  }
  interface TypertRemoteNamespaceMap {
    'mcpAdmin': TypertRemoteNamespace$6d637041646d696e
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
